### ISSUE TITLE
can`t download pcre

### ISSUE THREAD

**Issue by vadpro** [seedofjoy/openshift-diy-nginx-uwsgi-django#3]
in file  .openshift/action_hooks/pre_build , 33 line

> if [ ! -d $OPENSHIFT_DATA_DIR/nginx/sbin ]; then
>     cd $OPENSHIFT_TMP_DIR
>     wget ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-${PCRE_VERSION}.tar.gz
>     wget http://lnamp-web-server.googlecode.com/files/pcre-8.32.tar.gz
>     wget http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz

link - "ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-${PCRE_VERSION}.tar.gz" is not available.

Solution : Change link to **http://lnamp-web-server.googlecode.com/files/pcre-8.32.tar.gz**

**Comment by seedofjoy** [comment]
Fixed by updating version to 8.36. Thanks.
